project:
  type: website

website:
  title: "SQL Cheat Sheet"
  navbar:
    left:
      - href: index.qmd
        text: Basic syntax

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

